# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 82everywin Develop Blog
description: >- # this means to ignore newlines until "baseurl:"
  This blog is "한현승" blog.
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: View
    - name: Picture
    - name: Music
    - name: Settings
    - name: work
    - name: blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: 82everywin@naver.com
      link: mailto:82everywin@naver.com
    - name: WeChat
      value: KaKao - 82gustmd
      # link:
  follow:
    - name: Instargram
      link: http://twitter.com/ivory_roww
      username: "@YourTwitterUsername"
    - name: GitHub
      link: http://github.com/82everywin

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - GemfileS
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
